# Generated by Django 5.1.6 on 2025-04-08 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_appliedjob_status'),
        ('recruiter', '0004_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Declined', 'Declined')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appliedjob',
            unique_together={('student', 'job')},
        ),
    ]
