# Generated by Django 5.1.6 on 2025-04-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
