# Generated by Django 5.1.6 on 2025-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
